#!/bin/bash
#
#SBATCH  --workdir=/home/pranavk/MatrixEval

# Copy/paste this job script into a text file and submit with the command:
#    sbatch thefilename
# job standard output will go to the file slurm-%j.out (where %j is the job ID)

#SBATCH --time=16:00:00   # walltime limit (HH:MM:SS)
#SBATCH --nodes=1   # number of nodes
#SBATCH --ntasks-per-node=16   # 16 processor core(s) per node 
#SBATCH --job-name="matrix_evaluation_1"
#SBATCH --mail-user=pranavk@iastate.edu   # email address
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL

# LOAD MODULES, INSERT CODE, AND RUN YOUR PROGRAMS HERE
module load py-biopython/1.70-python2-6c67fd5
module load muscle
module load raxml

muscle -in Globins.fasta -matrix KMAT -out output/KMAT.fasta
muscle -in Globins.fasta -matrix BLOSUM62 -out output/BLOSUM62.fasta

cd output
#raxmlHPC-PTHREADS-AVX -p 12345 -# 100 -m PROTGAMMAWAG -s KMAT.fasta -n KMAT_raxML
#raxmlHPC-PTHREADS-AVX -p 12345 -# 100 -m PROTGAMMAWAG -s BLOSUM62.fasta -n BLOSUM62_raxML

raxmlHPC-PTHREADS-AVX -p 12345 -m PROTGAMMAWAG -s KMAT.fasta -n KMAT_raxML
raxmlHPC-PTHREADS-AVX -p 12345 -m PROTGAMMAWAG -s BLOSUM62.fasta -n BLOSUM62_raxML
